import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hearld Towers</title>
        <meta name="description" content="Generated by Hearld Towers" />
        <link rel="icon" href="/favicon.png" />
      </Head>
    </div>
  )
}
